---
title: "Machine Learning Assignment 1"
author: "Pamela Afful"
format: pdf
editor: visual
---

### Q1

```{r}

lq=function(x,q){
  coeff=2**q
  summands_store=c()
  for(k in 0:q) { # These are the ks we are summing over
  
   summands_k=(x**q)*(choose(q,k)*choose((q+k-1),q)  )
   summands_store=c(summands_store,summands_k)
  }
  
  f_x=coeff*sum(summands_store)
  
  return(f_x)
  
}

```

a\)

```{r}

# plot the above
# USE sapply to vectorize the calculation across a supplied vector
x_list=list(x=seq(-1,1,0.1))

x=seq(-1,1,0.1)
Qs=seq(1,5,1)

plot(NULL,xlim=c(-1,1),ylim=c(min(sapply(x,lq,q=5)),max(sapply(x,lq,q=5))),xlab='x',ylab='Lq(x)',main='Lq(x) Polynomials')
for(q_i in Qs){
  lines(x,sapply(x,lq,q=q_i),col='blue',lwd=1.2)

}


```

They are nonlinear curves at varying degrees

b\)

```{r}
set.seed(2)

alpha_qs=runif(3,-1,1)
beta_qs=runif(3,-1,1)

target_alpha=function(x,alpha_q,Qf){
  store_q=c()
  for(q_i in 0:Qf){
    
    store_q=c(store_q,alpha_q*(x**q_i))
  }
  
  ret=sum(store_q)
  return(ret)
}


target_beta=function(x,beta_q,Qf){
  store_q=c()
  for(q_i in 0:Qf){
    Lq=lq(x,q_i)
    store_q=c(store_q,beta_q*Lq)
  }
  
  ret=sum(store_q)
  return(ret)
}


# Plot the above target_alpha

plot(NULL,xlim=c(-1,1),ylim=c(-10,10),xlab='x',ylab='f(x)',main='Eqn(2) Random Target Functions')

for(alpha in alpha_qs){
  lines(x,sapply(x,target_alpha,alpha_q=alpha,Qf=5),col='blue',lwd=1.2)
}

# Plot the above target_beta


plot(NULL,xlim=c(-1,1),ylim=c(-100,100),xlab='x',ylab='f(x)',main='Eqn(2) Random Target Functions')

for(beta in beta_qs){
  lines(x,sapply(x,target_beta,beta_q=beta,Qf=5),col='red',lwd=1.2)
}


```

### Q3

```{r}
set.seed(2023)
f_x=function(x,sig=0){
  epsi=rnorm(1,0,sig)
  
  if(x<0){
    target=abs(x+1)-0.5
    return (target+epsi)
    
  }
  if(x>=0){
    target=abs(x-1)-0.5
    
    return(target+sig)
    
  }
}

# Simulte 5 time
n_sim=seq(1,5,1)
N=5

plot(NULL, xlim=c(-2,2),ylim=c(-1,1),xlab='xi',ylab='f(xi)',main='Target Function Simulation')

colours=c('green','blue','lightblue','orange','red')
for(i in seq_along(n_sim)){
  xi=sort(runif(N,-2,2))
  y=sapply(xi,f_x)
  lines( y~xi,lwd=1,col=colours[1])
  points(y~xi,lwd=1,col=colours[1],pch=1)
  
  h1=lm(y~xi)
  h1_predict=unname(predict(h1,data.frame(xi)))
  lines(h1_predict~xi,lwd=1,col=colours[3])
  points(h1_predict~xi,lwd=1,col=colours[3],pch=1)
  
  h2=lm(y~sin(pi*xi)+cos(pi*xi))
  h2_predict=unname(predict(h2,data.frame(xi)))
  lines(h2_predict~xi,lwd=1,col=colours[4])
  points(h2_predict~xi,lwd=1,col=colours[4],pch=1)
  
  
  
  
  
}

# Hypotheses





```
